# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaussian_process_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gaussian_process_data.proto',
  package='com.wattpad.bayesian_optimizer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bgaussian_process_data.proto\x12\x1e\x63om.wattpad.bayesian_optimizer\"+\n\x0bValueBounds\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\"R\n\x05Input\x12\x0c\n\x04name\x18\x01 \x01(\t\x12;\n\x06\x62ounds\x18\x02 \x01(\x0b\x32+.com.wattpad.bayesian_optimizer.ValueBounds\"1\n\x0e\x43ompletedTrial\x12\x0e\n\x06inputs\x18\x01 \x03(\x01\x12\x0f\n\x07targets\x18\x02 \x03(\x01\"\xc1\x02\n\x13GaussianProcessData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x06inputs\x18\x02 \x03(\x0b\x32%.com.wattpad.bayesian_optimizer.Input\x12\x14\n\x0ctarget_names\x18\x03 \x03(\t\x12\r\n\x05sigma\x18\x04 \x01(\x01\x12\x17\n\x0fkernel_constant\x18\x05 \x01(\x01\x12\x15\n\rlength_scales\x18\x06 \x03(\x01\x12H\n\x13length_scale_bounds\x18\x07 \x01(\x0b\x32+.com.wattpad.bayesian_optimizer.ValueBounds\x12H\n\x10\x63ompleted_trials\x18\x08 \x03(\x0b\x32..com.wattpad.bayesian_optimizer.CompletedTrialb\x06proto3')
)




_VALUEBOUNDS = _descriptor.Descriptor(
  name='ValueBounds',
  full_name='com.wattpad.bayesian_optimizer.ValueBounds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower', full_name='com.wattpad.bayesian_optimizer.ValueBounds.lower', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper', full_name='com.wattpad.bayesian_optimizer.ValueBounds.upper', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=106,
)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='com.wattpad.bayesian_optimizer.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.wattpad.bayesian_optimizer.Input.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounds', full_name='com.wattpad.bayesian_optimizer.Input.bounds', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=190,
)


_COMPLETEDTRIAL = _descriptor.Descriptor(
  name='CompletedTrial',
  full_name='com.wattpad.bayesian_optimizer.CompletedTrial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inputs', full_name='com.wattpad.bayesian_optimizer.CompletedTrial.inputs', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targets', full_name='com.wattpad.bayesian_optimizer.CompletedTrial.targets', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=241,
)


_GAUSSIANPROCESSDATA = _descriptor.Descriptor(
  name='GaussianProcessData',
  full_name='com.wattpad.bayesian_optimizer.GaussianProcessData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_names', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.target_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sigma', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.sigma', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_constant', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.kernel_constant', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_scales', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.length_scales', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_scale_bounds', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.length_scale_bounds', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='completed_trials', full_name='com.wattpad.bayesian_optimizer.GaussianProcessData.completed_trials', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=565,
)

_INPUT.fields_by_name['bounds'].message_type = _VALUEBOUNDS
_GAUSSIANPROCESSDATA.fields_by_name['inputs'].message_type = _INPUT
_GAUSSIANPROCESSDATA.fields_by_name['length_scale_bounds'].message_type = _VALUEBOUNDS
_GAUSSIANPROCESSDATA.fields_by_name['completed_trials'].message_type = _COMPLETEDTRIAL
DESCRIPTOR.message_types_by_name['ValueBounds'] = _VALUEBOUNDS
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['CompletedTrial'] = _COMPLETEDTRIAL
DESCRIPTOR.message_types_by_name['GaussianProcessData'] = _GAUSSIANPROCESSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueBounds = _reflection.GeneratedProtocolMessageType('ValueBounds', (_message.Message,), dict(
  DESCRIPTOR = _VALUEBOUNDS,
  __module__ = 'gaussian_process_data_pb2'
  # @@protoc_insertion_point(class_scope:com.wattpad.bayesian_optimizer.ValueBounds)
  ))
_sym_db.RegisterMessage(ValueBounds)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), dict(
  DESCRIPTOR = _INPUT,
  __module__ = 'gaussian_process_data_pb2'
  # @@protoc_insertion_point(class_scope:com.wattpad.bayesian_optimizer.Input)
  ))
_sym_db.RegisterMessage(Input)

CompletedTrial = _reflection.GeneratedProtocolMessageType('CompletedTrial', (_message.Message,), dict(
  DESCRIPTOR = _COMPLETEDTRIAL,
  __module__ = 'gaussian_process_data_pb2'
  # @@protoc_insertion_point(class_scope:com.wattpad.bayesian_optimizer.CompletedTrial)
  ))
_sym_db.RegisterMessage(CompletedTrial)

GaussianProcessData = _reflection.GeneratedProtocolMessageType('GaussianProcessData', (_message.Message,), dict(
  DESCRIPTOR = _GAUSSIANPROCESSDATA,
  __module__ = 'gaussian_process_data_pb2'
  # @@protoc_insertion_point(class_scope:com.wattpad.bayesian_optimizer.GaussianProcessData)
  ))
_sym_db.RegisterMessage(GaussianProcessData)


# @@protoc_insertion_point(module_scope)
